---
title: "Exam"
author: "Bishal sarker"
date: "2022-11-19"
output: 
  pdf_document:
    toc: True
---

```{r setup, include=FALSE, collapse=F}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

#  Model slection 


```{r comment=NA, }
library(leaps)

# best subset
model  = regsubsets(mpg~., data = mtcars)
model
d=summary(model)
which.max(d$rsq)
d$rsq

# forward selection
all = lm(mpg ~1 ,data = mtcars)
av  = lm(mpg ~., data = mtcars)
model_step = step(all, direction = 'forward', scope = formula(av))
model_step$anova


#perform backward stepwise regression

backward <- step(all, direction='backward', scope=formula(all))

backward$anova
backward$coefficients

## Both 

intercept_only <- lm(mpg ~ 1, data=mtcars)
#define model with all predictors
all <- lm(mpg ~ ., data=mtcars)
#perform backward stepwise regression
both <- step(intercept_only, direction='both', scope=formula(all), trace=0)
#view results of backward stepwise regression
both$anova

```


# K fold cross validation 


```{r}
library(caret)
model  = train(
  mpg ~ drat, mtcars, method = "lm",
trControl=  trainControl("cv")
)
model
```


# Lda vs KNN

```{r}
library(caTools)
train = sample.split(iris$Species, SplitRatio = .75)
trin = iris[train ==TRUE,]

x = trin[,-5]
y = trin[,5]
tst = iris[train==FALSE,][,-5]
yt = iris[train==FALSE,][,5]
## KNN
library(class)
knnMo = knn(x,tst,y, k =1)
knnMo


table(yt, knnMo)
mean(knnMo !=yt)

# lDA
library(MASS)
lid = lda(Species ~ . , trin)
pr = predict(lid,tst)
table(pr$class, yt)
mean(pr$class != yt)

# QDA 

liq = qda(Species ~ . , trin)
prq = predict(liq,tst)
table(prq$class, yt)
 error = mean(prq$class != yt)
```

# Bayesian posterior

## # Beta binomial mode

```{r}


n = 20
Y = 4
a = 3
b =1

grid = seq(0,1,.1)

prior = dbeta(grid, a,b)
prior = prior/ sum(prior) # standarized

like = dbinom(4, 20, grid)
like = like/sum(like)

post = like*prior
post = post/sum(post)

plot(grid, like)

# Exact calculation 

post = dbeta(grid, (Y+a), (n+b-Y) )
post
plot(grid, post)

man = (Y +a)/(n- Y +b)

va = (Y + a)/(n - Y+b)^2
 
qbeta(c(.05,.95),Y+a, n-Y+b)


```
## Gamma poisson

```{r}
N = 20
y =11
a = .5
b = .5
l = seq(.1,2,.01)
like = dpois(y, N*l)
like = like/sum(like)

prior = dgamma(l, .5,.5)
prior = prior/sum(prior)

post = like * prior
post = post / sum(post)

plot(l, post)

li = ( y + a)/(N + b)
sq = (y + a)/ (N+b)^2
sqrt(sq)

```
## Normal normal]

```{r}
y = .1
sigma = .005

m = .05
s = .025
gri = seq(0,.15, .001)
like = dnorm(y, gri, sigma)
like = like /sum(like)

pr = dnorm(gri, m, s)
pr =  post/sum(post)

post = pr * like
post = post/sum(post)


su  = 1/sigma^2 + 1/s^2
ms = (y/sigma^2 + m/s^2 )
mu = ms/su
mu
```



# Joint distribution

```{r}

dat      <- read.csv("http://www4.stat.ncsu.edu/~reich/ST590/assignments/Obama2012.csv")
pctObama <- 100*dat[,2]
pctUnEmp <- dat[,18]

############################################
# Convert to discrete variables
############################################

X        <- ifelse(pctObama>50,1,0)
Y        <- ifelse(pctUnEmp>10,1,0)+
  ifelse(pctUnEmp>15,1,0)
plot(Y,pctUnEmp)

# Compute the sample joint distribution

table(X,Y)/100
# Compute the sample marginal distributions

table(X)/100
table(Y)/100

# Compute the conditional probabilities

mean(X[Y==0])
mean(X[Y==1])
mean(X[Y==2])



############################################
# Plot for continuous variables
############################################

X <- pctObama
Y <- pctUnEmp

#Joint

plot(X,Y,main="Joint distribution")

# Marginals

hist(X,main="Marginal distribution of X")
hist(Y,main="Marginal distribution of Y")

# Probability in a set

inA <- (X>50) & (Y>10) & (Y<15)  
plot(X,Y,col=ifelse(inA,2,1),main="Prob in set A")
polygon(c(50,50,100,100,50),c(10,15,15,10,10))

# Approximate conditional pdf

Y10 <- Y>9.5 & Y<10.5
plot(X,Y,col=ifelse(Y10,2,1))
abline(9.5,0)
abline(10.5,0)

X10 <- X[Y10]
hist(X10,main="f(x|Y=10)",xlim=range(X),prob=TRUE)


```


# Bivariate normal

```{r}
binorm<-function(x,y,muX=0,muY=0,sigmaX=1,sigmaY=1,rho=0){

  c    <- sigmaX*sigmaY*sqrt(1-rho^2)*2*pi
  d    <- 1/(1-rho^2)
  z_x  <- (x-muX)/sigmaX
  z_y  <- (y-muY)/sigmaY

  pdf <- (1/c)*exp(-0.5*d*(z_x^2+z_y^2-2*rho*z_x*z_y))

return(pdf)}


 m    <- 100
 pts  <- seq(-3,3,length=m)
 grid <- expand.grid(pts,pts)
 plot(grid)
 
 
 
 muX    <- 0
 muY    <- 0
 sigmaX <- 1
 sigmaY <- 1
 rho    <- 0.9

 pdf    <- binorm(grid[,1],grid[,2],muX,muY,sigmaX,sigmaY,rho)
 pdf    <- matrix(pdf,m,m)

 library(fields)
 image.plot(pts,pts,pdf,
            xlab="x",ylab="y",
            main="Bivariate normal PDF",
            col=gray(1-seq(0,1,.05)))
 
 
 ## MARGINAL 
 fx <- colSums(pdf)
 fx <- fx/sum(fx)

 plot(pts,fx,type="l",xlab="x",ylab="f(x)")

 ##Conditional distribution
  
 par(mfrow=c(2,2))
  image.plot(pts,pts,pdf,
             xlab="x",ylab="y",
             main="Bivariate normal PDF",
             col=gray(1-seq(0,1,.05)))

  abline(pts[80],0,lty=2)
  abline(pts[50],0,lty=2)
  abline(pts[20],0,lty=2)

  cond20 <- pdf[20,]
  cond20 <- cond20/sum(cond20)
  plot(pts,cond20,type="l",xlab="x",ylab="f(x|y)",
       main=paste("Y =",round(pts[20],3)))

  cond50 <- pdf[50,]
  cond50 <- cond50/sum(cond50)
  plot(pts,cond50,type="l",xlab="x",ylab="f(x|y)",
       main=paste("Y =",round(pts[50],3)))

  cond80 <- pdf[80,]
  cond80 <- cond80/sum(cond80)
  plot(pts,cond80,type="l",xlab="x",ylab="f(x|y)",
       main=paste("Y =",round(pts[80],3)))

```


# HIV data

```{r}
## Compute the posterior probability the patient has HIV given a positive test

post_prob<-function(p,q0,q1){
  p*q1/(p*q1+(1-p)*q0)  
}

## Base case

p  <- 0.50   # Prior probability
q0 <- 0.01   # False positive probability
q1 <- 0.90   # True positive probability


## Effect of the prior
grid  <- seq(0.01,0.99,.01)

plot(grid,post_prob(grid,q0,q1),
     type="l",
     xlab="Prior probability",
     ylab="Posterior probability") 

post_prob(p,q0,q1)


## Effect of the likelihood - false positive rate

plot(grid,post_prob(p,grid,q1),
     type="l",
     xlab="False positive rate",
     ylab="Posterior probability") 

## Effect of the likelihood - true positive rate
plot(grid,post_prob(p,q0,grid),
     type="l",
     xlab="True positive rate",
     ylab="Posterior probability") 

#Monte Carlo approximation:

n     <- 10000
theta <- NULL
Y     <- NULL

#start sampling
for(i in 1:n){
   theta[i] <- rbinom(1,1,p)
   prob     <- ifelse(theta[i]==1,q1,q0)
   Y[i]     <- rbinom(1,1,prob)
}

table(Y,theta)/n  

```